### ISSUE TITLE
Sea Fox IlClan era, add unit bug 

### ISSUE THREAD

**Issue by SaracensFTW** [piotrberlowski/mul-search#1]
For Clan Sea Fox, ilClan era, IS Clan General

You can search and sort, but gives an error if you try to add any unit to your list that is something like

cannot add unit, try clearing the list or setting search to legacy.

Tried a different faction and it gave the same error (also ilClan). Possibly Android phone issue? Android v14, Pixel Pro 6

**Comment by piotrberlowski** [comment]
Thanks for reporting!I think there is a bug here to do with list criteria protection - when the list is empty it should default the criteria to your search. 

_However_ what you _can_ do to circumnavigate this is to go to the list builder and click the "Clear" button. That will set the criteria and you should be able to construct.
