### ISSUE TITLE
Request: Add “filter” for “Rules Level”

### ISSUE THREAD

**Issue by OftKilted** [piotrberlowski/mul-search#17]
Request for “Rules Level” filtering.

IE Introductory, Standard, Advanced, Experimental , Unknown

the AS350 packet restricts one from being able to select units using Experimental rules.

Being able to select a level either as a “check box” for a specific level, or as a “level and all levels below would help. (Or even a everything except Experimental & Unknown)

**Comment by piotrberlowski** [comment]
Good point. I'll look into this, should be easy.
