### ISSUE TITLE
Main Screen too wide on Mobile/Tablet devices

### ISSUE THREAD

**Issue by Hwatwasthat** [piotrberlowski/mul-search#29]
Hey, since the latest update (0.4.4 I believe) the page has been rendering too widely on mobile devices, and the lower bar has become detached, making it float around 1/8th of the way up the screen. I haven't noticed any problems on desktop.

I think the issue is related to the additional add button for units, as the offset seems to match the width of this buttons area. I will have a look at troubleshooting myself if I get the time but figured I'd drop an issue in as well. I'm using Firefox for Android in both.

Just tried on Chrome and having the same issue for the width, but not the lower bar.

![Screenshot (20 May 2024 15 28 11)](https://github.com/piotrberlowski/mul-search/assets/29790143/d3083e0d-4846-4ff3-8aba-07b7bafeedb2)
![Screenshot (20 May 2024 15 29 10)](https://github.com/piotrberlowski/mul-search/assets/29790143/e64c1fa3-93ce-404a-80f7-933e4f5ce0e2)

**Comment by piotrberlowski** [comment]
Thanks for reporting. I was able to reproduce. Not quite sure which tailwind black magic caused it but hopefully I have a fix (related to a new way of handling UI)

**Comment by piotrberlowski** [comment]
It took me 8 hours of messing with CSS to figure this one out. Turns out it's the fecking tooltips that I added to some of the inputs. They stick outside the screen even though they are hidden... :/
