### ISSUE TITLE
Safari Browser MacOS Display Issues : Missing Era,Faction and General List and PV/Unit Count

### ISSUE THREAD

**Issue by OftKilted** [piotrberlowski/mul-search#36]
When using the Safari Browser the red Faction, Era and General List box is hidden behind the 'List Builder for AS' floating bar.

The 'Builder' that shows Units and PV count is also unavailable.

Browser on the Left::
Safari Version 17.6 (19618.3.11.11.5)

Browser on Right:
Microsoft Edge: Version 127.0.2651.98 (Official build) (arm64)

![Screenshot 2024-08-12 at 6 35 48 PM](https://github.com/user-attachments/assets/29c41525-dca2-499d-b468-72193f125a39)

**Comment by piotrberlowski** [comment]
Apologies. I think you also mentioned that this is true for both mobile and desktop, right?

I will attempt to get access to Safari and see if I can figure this out.

**Comment by OftKilted** [comment]
yep, this appears to be similar / same as the issue seen in iOS

![IMG_5323](https://github.com/user-attachments/assets/aab6479d-5d5a-4dc0-9309-ccfb17627a7e)

**Comment by OftKilted** [comment]
Update:
For iOS, the main page (before the results are returned) looks correct and has the correct heights and behavior for the drop-down.
![IMG_5513](https://github.com/user-attachments/assets/2a149300-0163-4eee-90ca-97e45905b370)
![IMG_5514](https://github.com/user-attachments/assets/c119c4e0-d1e7-4d6e-8544-aa18cac1578f)

**Comment by OftKilted** [comment]
When in the results page the drop-down menu shows behind the results. Expected result would be that the drop-down menu show infront of the current list.
![IMG_5515](https://github.com/user-attachments/assets/2c5308e2-afe4-44c0-90f5-edab9fa18cc7)

The “change era” pops up and works well infront of the list.
![IMG_5516](https://github.com/user-attachments/assets/b8b7ff4f-6f8b-4837-a5f6-c532640bc5eb)

**Comment by piotrberlowski** [comment]
I'm assuming these are artifacts of me using non-Safari compatible CSS. I will get a subscription to something like LambdaTest and I'll try to test on Safari.

**Comment by piotrberlowski** [comment]
This was reproduced on Chrome/Windows and fixed. Safari emulator on MacOS/Sequoia in LambdaTest is also showing the UI correctly.
![macOS-Sequoia(1)](https://github.com/user-attachments/assets/e707e16d-a555-4528-91e6-ddf02b53a3f4)
![macOS-Sequoia](https://github.com/user-attachments/assets/782ba16e-f142-4ad4-8373-1ff096831b3c)
